#!/bin/bash
# EnviroPi Daily Report Generator
# Pulls sensor data from Pi and sends formatted email

set -e

PI_HOST="enviropi@192.168.2.15"
TODAY=$(date +"%Y-%m-%d")
DATA_FILE="/home/enviropi/enviro_data/enviro_${TODAY}.json"
LOCAL_DATA="/tmp/enviro_${TODAY}.json"
REPORT_HTML="/tmp/enviro_report.html"

echo "Fetching sensor data from EnviroPi..."
scp "${PI_HOST}:${DATA_FILE}" "${LOCAL_DATA}" 2>/dev/null || {
    echo "No data file for today yet"
    exit 1
}

echo "Generating report..."
python3 << 'PYTHON_SCRIPT'
import json
import sys
from datetime import datetime

# Read data
with open('/tmp/enviro_' + datetime.now().strftime('%Y-%m-%d') + '.json', 'r') as f:
    data = json.load(f)

readings = data['readings']
if not readings:
    print("No readings yet today")
    sys.exit(1)

# Calculate stats
temps = [r['temperature_c'] for r in readings if 'temperature_c' in r and r['temperature_c'] is not None]
pressures = [r['pressure_hpa'] for r in readings if 'pressure_hpa' in r and r['pressure_hpa'] is not None]
humidities = [r.get('humidity_pct') for r in readings if r.get('humidity_pct') is not None]
lights = [r['light_lux'] for r in readings if 'light_lux' in r and r['light_lux'] is not None]

temp_avg = sum(temps) / len(temps) if temps else 0
temp_min = min(temps) if temps else 0
temp_max = max(temps) if temps else 0

pressure_avg = sum(pressures) / len(pressures) if pressures else 0
pressure_min = min(pressures) if pressures else 0
pressure_max = max(pressures) if pressures else 0

humidity_avg = sum(humidities) / len(humidities) if humidities else 0
humidity_min = min(humidities) if humidities else 0
humidity_max = max(humidities) if humidities else 0

light_avg = sum(lights) / len(lights) if lights else 0
light_max = max(lights) if lights else 0

# Generate HTML
html = f"""<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 600px; margin: 20px auto; }}
        h1 {{ color: #333; }}
        .stats {{ background: #f5f5f5; padding: 15px; border-radius: 8px; margin: 20px 0; }}
        .metric {{ margin: 10px 0; }}
        .value {{ font-size: 24px; font-weight: bold; color: #007AFF; }}
        .label {{ font-size: 12px; color: #666; text-transform: uppercase; }}
        .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; }}
    </style>
</head>
<body>
    <h1>🥧 EnviroPi Daily Report</h1>
    <p><strong>Date:</strong> {data['date']}</p>
    <p><strong>Readings:</strong> {len(readings)} samples collected</p>
    
    <div class="stats">
        <h2>🌡️ Temperature</h2>
        <div class="metric">
            <div class="value">{temp_avg:.1f}°C</div>
            <div class="label">Average</div>
        </div>
        <p>Min: {temp_min:.1f}°C | Max: {temp_max:.1f}°C</p>
    </div>
    
    <div class="stats">
        <h2>🌍 Pressure</h2>
        <div class="metric">
            <div class="value">{pressure_avg:.1f} hPa</div>
            <div class="label">Average</div>
        </div>
        <p>Min: {pressure_min:.1f} hPa | Max: {pressure_max:.1f} hPa</p>
    </div>
    
    <div class="stats">
        <h2>💧 Humidity</h2>
        <div class="metric">
            <div class="value">{humidity_avg:.1f}%</div>
            <div class="label">Average</div>
        </div>
        <p>Min: {humidity_min:.1f}% | Max: {humidity_max:.1f}%</p>
    </div>
    
    <div class="stats">
        <h2>💡 Light</h2>
        <div class="metric">
            <div class="value">{light_avg:.1f} lux</div>
            <div class="label">Average</div>
        </div>
        <p>Peak: {light_max:.1f} lux</p>
    </div>
    
    <div class="footer">
        <p>Generated by EnviroPi on Raspberry Pi Zero 2 W</p>
        <p>Pimoroni Enviro+ • BME280 (temp/pressure/humidity) • LTR-559 (light)</p>
    </div>
</body>
</html>
"""

with open('/tmp/enviro_report.html', 'w') as f:
    f.write(html)

print("Report generated!")
PYTHON_SCRIPT

echo "Sending email via Gmail..."
export GOG_ACCOUNT=support@youragentworks.com
HTML_BODY=$(cat "${REPORT_HTML}")
gog gmail send \
    --to chris.remboldt@gmail.com \
    --subject "🥧 EnviroPi Daily Report - ${TODAY}" \
    --body-html "${HTML_BODY}"

echo "✅ Daily report sent!"
rm -f "${LOCAL_DATA}" "${REPORT_HTML}"
